name: alexander.y
favicon: null
layout_spectrum: 1
typography_spectrum: 0.62438
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#AFC9D8'
    - '#A58A6F'
    - '#273A41'
    - '#5D8FA4'
  brandStrength: 0.1861199201084673
  lightness: 0.9643738972954452
  saturation: 0.998184205731377
  rhythmicContrast: 0.08883767551742494
purpose: []
